"""set null on delete for notification related_secret_id

Revision ID: 0e85b0277e50
Revises: e4472561ecf6
Create Date: 2026-07-29 10:42:11.154129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e85b0277e50'
down_revision: Union[str, Sequence[str], None] = 'e4472561ecf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_related_secret_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'secrets', ['related_secret_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_related_secret_id_fkey'), 'notifications', 'secrets', ['related_secret_id'], ['id'])
    # ### end Alembic commands ###
