"""make secret fields nullable

Revision ID: 1a871e2f8544
Revises: a2ae6b766501
Create Date: 2026-07-21 11:28:44.780589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a871e2f8544'
down_revision: Union[str, Sequence[str], None] = 'a2ae6b766501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'nonce',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('secrets', 'encrypted_value',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'encrypted_value',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('secrets', 'nonce',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
