"""make vault fields nullable

Revision ID: 4a1240a9c314
Revises: 1d4fe58e174f
Create Date: 2026-07-21 06:08:27.087749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a1240a9c314'
down_revision: Union[str, Sequence[str], None] = '1d4fe58e174f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'vault_salt',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('owners', 'server_half',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('owners', 'key_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'key_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owners', 'server_half',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('owners', 'vault_salt',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
