"""add encrypted value to secrets

Revision ID: 6066d623ed68
Revises: 16a0a97dcb79
Create Date: 2026-07-08 07:08:47.047443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6066d623ed68'
down_revision: Union[str, Sequence[str], None] = '16a0a97dcb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('encrypted_value', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'encrypted_value')
    # ### end Alembic commands ###
