"""add revoked_at

Revision ID: 9a02b1835b88
Revises: 1a871e2f8544
Create Date: 2026-07-21 11:35:13.777189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a02b1835b88'
down_revision: Union[str, Sequence[str], None] = '1a871e2f8544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'revoked_at')
    # ### end Alembic commands ###
