"""add secret name to audit log

Revision ID: 9cb92cb486f0
Revises: 9a02b1835b88
Create Date: 2026-07-21 11:48:14.992325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb92cb486f0'
down_revision: Union[str, Sequence[str], None] = '9a02b1835b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('secret_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'secret_name')
    # ### end Alembic commands ###
