"""add cascade delete to audit log

Revision ID: a2ae6b766501
Revises: 4a1240a9c314
Create Date: 2026-07-21 07:41:06.404334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ae6b766501'
down_revision: Union[str, Sequence[str], None] = '4a1240a9c314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_log_secret_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'secrets', ['secret_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_secret_id_fkey'), 'audit_log', 'secrets', ['secret_id'], ['id'])
    # ### end Alembic commands ###
